#!/usr/bin/env python3
"""
This module provides a coroutine that collects 10 random numbers using async
comprehension over async_generator.
"""

import typing
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> list[float]:
    """
    Collects and returns 10 random numbers generated by async_generator
    using async comprehension.
    """
    result = []
    async for value in async_generator():
        result.append(value)
    return result
